### ISSUE TITLE
Errors in nitroApi Swagger file

### ISSUE THREAD

**Issue by IvanGoncharov** [MikeRalphson/bbcapis#4]
``` yaml
- code: OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION
  message: 'Missing required property definition: template_url'
  path:
    - definitions
    - image_link
    - properties
    - image
- code: OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION
  message: 'Missing required property definition: image'
  path:
    - definitions
    - image_link
    - properties
    - image
```

**Comment by MikeRalphson** [comment]
Still passing the bigstickcarpet swagger validator, and the JSON schema and resultant swagger specs are passing validation against their schema.

The error is caused by the change to the handling of optional attributeGroups from the source XML Schema (XSD):

``` javascript
            "properties": {
                "image": {
                    "type": "object",
                    "required": [
                        "template_url",
                        "image"
                    ],
                    "additionalProperties": false,
                    "x-anyOf": [
                        {
                            "$ref": "#/definitions/deprecationAttributes"
                        },
                        {
                            "properties": {
                                "pid": {
                                    "$ref": "#/definitions/pid"
                                },
                                "template_url": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "object",
                                    "properties": {
                                        "pid": {
                                            "$ref": "#/definitions/pid"
                                        },
                                        "template_url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "template_url"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        }
                    ]
```

The easiest fix for now would be to remove the `required` array where an `x-anyOf` has been inserted. 

@IvanGoncharov Thanks for spotting this.

**Comment by MikeRalphson** [comment]
@IvanGoncharov please let me know if this fixes the issue.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Yes, it solves the problem. But introduce one more vendor extension.
One alternative to consider is adding these properties with empty schemas:

``` yaml
properties:
  template_url: {}
  image: {}
```
